info:
  description: API contract for order-service
  title: order-service API
  version: 1.0.0
openapi: 3.0.0
paths:
  /orders:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                items:
                  items:
                    properties:
                      productId:
                        type: string
                      quantity:
                        minimum: 1
                        type: integer
                    required:
                    - productId
                    - quantity
                    type: object
                  type: array
                userId:
                  type: string
              required:
              - userId
              - items
              type: object
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    format: date-time
                    type: string
                  orderId:
                    type: string
                  status:
                    enum:
                    - pending
                    type: string
                type: object
          description: Order created successfully
        "400":
          description: Invalid request
      summary: Create a new order
  /orders/{orderId}:
    get:
      parameters:
      - in: path
        name: orderId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    format: date-time
                    type: string
                  items:
                    items:
                      properties:
                        productId:
                          type: string
                        quantity:
                          type: integer
                      type: object
                    type: array
                  orderId:
                    type: string
                  status:
                    enum:
                    - pending
                    - processing
                    - shipped
                    - delivered
                    - cancelled
                    type: string
                  userId:
                    type: string
                type: object
          description: Order details
        "404":
          description: Order not found
      summary: Get order by ID
servers:
- url: http://localhost:8080
